# Generated by Django 4.1.2 on 2024-01-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.course'),
        ),
    ]
