# Generated by Django 4.1.2 on 2023-05-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_level_alter_customer_referral_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance_HRWT',
            new_name='balance_Usdt',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='balance_hrw',
            new_name='balance_hrwt',
        ),
    ]
