# Generated by Django 4.1.2 on 2024-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='img/dflt_img.jpeg', upload_to='user_photos'),
        ),
    ]
