# Generated by Django 4.1.7 on 2023-03-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_verified_seller_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "token",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("desc1", models.TextField(blank=True, max_length=100, null=True)),
                ("desc2", models.TextField(blank=True, max_length=100, null=True)),
                ("desc3", models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
