# Generated by Django 4.1.2 on 2023-05-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_balance_hrwt_customer_balance_usdt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance_Usdt',
            new_name='balance_usdt',
        ),
        migrations.AlterField(
            model_name='customer',
            name='referrer_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
