# Generated by Django 4.1.7 on 2023-03-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_packet"),
    ]

    operations = [
        migrations.AddField(
            model_name="packet",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
