# Generated by Django 4.1.2 on 2023-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_country_customer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
