# Generated by Django 4.1.7 on 2023-03-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_packet_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Packet",
        ),
    ]
