# Generated by Django 4.1.2 on 2024-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_referrer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='user_photos/dflt_img.jpeg', upload_to='user_photos'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referrer_code',
            field=models.CharField(blank=True, default='admin', max_length=5),
        ),
    ]
