# Generated by Django 4.0.4 on 2022-05-08 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_wishlist_quantity_alter_wishlist_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WishItem',
        ),
    ]
