# Generated by Django 4.1.7 on 2023-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_delete_packet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "token",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("desc1", models.CharField(max_length=200)),
                ("desc2", models.CharField(max_length=200)),
                ("desc3", models.CharField(max_length=200)),
            ],
        ),
    ]
