# Generated by Django 4.1.2 on 2023-05-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_default_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referrer_code',
            field=models.CharField(blank=True, default='admin', max_length=5),
        ),
    ]
