# Generated by Django 4.1.2 on 2024-01-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_image_alter_customer_referrer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referrer_code',
            field=models.CharField(blank=True, default='Academy', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
