# Generated by Django 4.1.7 on 2023-03-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_packet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packet",
            old_name="id",
            new_name="number",
        ),
    ]
