# Generated by Django 4.0.4 on 2022-05-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_wishlist_wishitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
