# Generated by Django 4.1.2 on 2024-01-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_zipcode_customer_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance_hrwt',
            new_name='balance_rub',
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance_tvt',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
