# Generated by Django 4.1.7 on 2023-03-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_rename_id_packet_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packet",
            name="token",
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
