# Generated by Django 4.0.4 on 2022-05-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_wishitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='sex',
        ),
    ]
