# Generated by Django 4.1.2 on 2023-05-13 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_wallet_balance_alter_wallet_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallets',
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
