# Generated by Django 4.1.2 on 2024-01-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_balance_hrwt_customer_balance_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance_rub',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance_usdt',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
