# Generated by Django 4.1.7 on 2023-03-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_packet_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Packet",
        ),
    ]
