# Generated by Django 4.1.7 on 2023-03-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_delete_packet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
