# Generated by Django 4.1.2 on 2023-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_customer_wallets_customer_wallet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance_hrwt',
            new_name='balance_tvt',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
