# Generated by Django 4.1.2 on 2024-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_balance_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referrer_code',
            field=models.CharField(blank=True, default='Academy', max_length=10),
        ),
    ]
