# Generated by Django 4.1.2 on 2023-05-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_balance_hrwt_customer_balance_tvt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.CharField(default='', max_length=100),
        ),
    ]
