# Generated by Django 4.1.2 on 2023-03-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_description'),
        ('store', '0011_rename_name_customer_first_name_customer_last_name'),
    ]

    operations = [
    ]
