# Generated by Django 4.0.4 on 2022-05-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customerdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='user',
        ),
    ]
