# Generated by Django 4.1.2 on 2023-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customer_balance_hrwt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='level',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Ученик', 'Ученик'), ('Преподаватель', 'Преподаватель'), ('Эксперт', 'Эксперт'), ('Продавец', 'Продавец')], default='Ученик', max_length=20),
            preserve_default=False,
        ),
    ]
