# Generated by Django 4.1.2 on 2024-01-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
