# Generated by Django 4.0.4 on 2022-05-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_customerdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.customer'),
        ),
    ]
