# Generated by Django 4.1.2 on 2024-01-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='store.friend'),
        ),
        migrations.AddField(
            model_name='friend',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
