# Generated by Django 4.1.2 on 2023-03-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_merge_20230331_1119'),
        
    ]

    operations = [
    ]
