# Generated by Django 4.1.2 on 2024-01-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer_friends_friend_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
