# Generated by Django 4.1.2 on 2023-03-31 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_customer_id_alter_category_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
