# Generated by Django 4.1.2 on 2023-03-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_support_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='customer',
            new_name='user',
        ),
    ]
