# Generated by Django 3.2.4 on 2024-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_chatmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_sender',
            field=models.BooleanField(default=False),
        ),
    ]
