# Generated by Django 4.1.2 on 2023-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_newsfeed_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='image',
            field=models.ImageField(null=True, upload_to='partners'),
        ),
    ]
