# Generated by Django 3.2.4 on 2024-01-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_chatmessage_is_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_sender',
        ),
    ]
