# Generated by Django 4.0.4 on 2022-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
