# Generated by Django 4.1.2 on 2023-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_partnership_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=25)),
                ('price_usd', models.CharField(max_length=25)),
                ('price_twt', models.CharField(max_length=25)),
                ('short_desc', models.CharField(max_length=100)),
                ('long_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
