# Generated by Django 3.2.4 on 2024-02-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_thread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
