# Generated by Django 4.1.2 on 2023-07-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
