# Generated by Django 4.1.2 on 2023-07-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_packagescat_packages_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='is_main',
        ),
    ]
