# Generated by Django 4.0.4 on 2022-05-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_customer_support_name_alter_offer_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='name',
            new_name='customer',
        ),
    ]
