# Generated by Django 3.2.4 on 2024-02-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
