# Generated by Django 4.1.2 on 2023-03-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_shippingaddress'),
        ('store', '0025_alter_comments_customer'),
    ]

    operations = [
    ]
