# Generated by Django 4.0.4 on 2023-01-15 09:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_partnership_product_brand_name_product_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1500, null=True),
        ),
    ]
