# Generated by Django 4.1.2 on 2023-11-14 11:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Category',
            field=models.CharField(choices=[('Основные курсы', 'Основные курсы'), ('Занятие телом', 'Занятие телом'), ('Игры', 'Игры')], default='Основные курсы', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_presentation', models.URLField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('courses', models.ManyToManyField(to='store.course')),
            ],
        ),
    ]
