# Generated by Django 4.0.4 on 2023-01-15 09:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_partnership_product_brand_name_product_file_and_more'),
    ]

   
