# Generated by Django 4.1.2 on 2023-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_customer_id_alter_category_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
