# Generated by Django 3.2.4 on 2024-02-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
