# Generated by Django 4.1.2 on 2023-01-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_slider_product_alter_comments_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
