# Generated by Django 4.1.2 on 2023-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_customer_id_alter_customer_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
