# Generated by Django 4.1.2 on 2023-02-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_slider_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='images/img.jpg', upload_to='user_photos'),
        ),
    ]
