# Generated by Django 4.1.2 on 2023-03-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_customer_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referring_customers', to='store.customer'),
        ),
    ]
