# Generated by Django 4.1.2 on 2023-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='user_photos/img.jpg', upload_to='user_photos'),
        ),
    ]
