# Generated by Django 4.1.2 on 2023-03-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_customer_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referral_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
