# Generated by Django 4.1.2 on 2023-11-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='Category',
            field=models.CharField(choices=[('Основные курсы', 'Основные курсы'), ('Занятие телом', 'Занятие телом'), ('Игры', 'Игры')], default='Основные курсы', max_length=20),
        ),
    ]
