# Generated by Django 4.1.2 on 2023-03-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_customer_referral_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referred_by',
        ),
    ]
