# Generated by Django 4.1.2 on 2024-02-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_chatbotmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBotMessage',
            new_name='Conversation',
        ),
    ]
