# Generated by Django 4.1.2 on 2024-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_rename_chatbotmessage_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('response', models.TextField()),
            ],
        ),
    ]
