# Generated by Django 4.1.2 on 2023-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
