# Generated by Django 4.1.2 on 2023-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_course_order_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
