# Generated by Django 4.1.2 on 2023-11-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_direction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='sale_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
