# Generated by Django 4.1.2 on 2024-02-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='keyword',
        ),
        migrations.AddField(
            model_name='trigger',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
