# Generated by Django 4.1.2 on 2023-03-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_product_product_id_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
