# Generated by Django 4.1.2 on 2023-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_stream_purchase_payment_lesson_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='isavaliable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
