# Generated by Django 4.1.2 on 2023-12-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_stream_isavaliable_stream_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='lessons',
            field=models.ManyToManyField(related_name='direction_lessons', to='store.lesson'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.direction'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='students',
            field=models.ManyToManyField(to='store.customer'),
        ),
    ]
