# Generated by Django 4.1.2 on 2023-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_studygroup_direction_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='zoom_links',
            field=models.ManyToManyField(related_name='meetings', to='store.zoomlink'),
        ),
    ]
