# Generated by Django 4.1.2 on 2023-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contry',
            new_name='country',
        ),
    ]
