# Generated by Django 4.1.2 on 2023-12-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_lesson_zoom_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='zoom_links',
            field=models.ManyToManyField(related_name='lessons', to='store.zoomlink'),
        ),
    ]
