# Generated by Django 4.1.2 on 2023-12-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_lesson_zoom_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='zoom_links',
        ),
        migrations.AddField(
            model_name='zoomlink',
            name='Lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.lesson'),
        ),
    ]
