# Generated by Django 4.1.2 on 2023-12-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_course_lesson_lesson_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Course',
            new_name='course',
        ),
    ]
