# Generated by Django 4.1.2 on 2023-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_rename_course_lesson_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZoomLink',
            new_name='VideoRec',
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель'), ('Эксперт', 'Эксперт'), ('Продавец', 'Продавец')], max_length=20),
        ),
    ]
