# Generated by Django 4.1.2 on 2023-04-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='referrer',
            new_name='referral_by',
        ),
    ]
