# Generated by Django 4.1.2 on 2023-12-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_rename_zoomlink_videorec_alter_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='isavaliable',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='start_date',
        ),
        migrations.AddField(
            model_name='stream',
            name='courses',
            field=models.ManyToManyField(to='store.course'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
