# Generated by Django 4.1.2 on 2023-04-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_rename_referrer_customer_referral_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
