# Generated by Django 4.1.2 on 2023-12-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_stream_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='lessons',
        ),
    ]
