# Generated by Django 4.1.2 on 2023-12-22 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_remove_direction_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stream'),
        ),
    ]
