# Generated by Django 4.1.2 on 2023-12-22 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_lesson_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.direction'),
        ),
    ]
