# Generated by Django 4.1.2 on 2023-12-23 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_customer_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.direction'),
        ),
    ]
