# Generated by Django 4.1.2 on 2023-12-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_lesson_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='students',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='stream',
        ),
        migrations.AddField(
            model_name='customer',
            name='directions',
            field=models.ManyToManyField(related_name='customers', to='store.direction'),
        ),
        migrations.AddField(
            model_name='direction',
            name='lessons',
            field=models.ManyToManyField(related_name='direction_lessons', to='store.lesson'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='courses',
            field=models.ManyToManyField(related_name='direction_courses', to='store.course'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='courses',
            field=models.ManyToManyField(related_name='stream_courses', to='store.course'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
