# Generated by Django 4.1.2 on 2023-12-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_remove_studygroup_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.direction'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stream'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='courses',
            field=models.ManyToManyField(to='store.course'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='courses',
            field=models.ManyToManyField(to='store.course'),
        ),
    ]
