# Generated by Django 4.1.2 on 2023-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_customer_direction_studygroup_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='open_status',
            field=models.BooleanField(default=False),
        ),
    ]
