# Generated by Django 4.1.2 on 2023-12-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_lesson_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='stream',
            new_name='streams',
        ),
    ]
