# Generated by Django 4.1.2 on 2023-12-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_rename_stream_lesson_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель'), ('Эксперт', 'Эксперт'), ('Продавец', 'Продавец')], default='Студент', max_length=20),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
