# Generated by Django 4.1.2 on 2023-12-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_alter_customer_status_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaklyBoard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.course')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.direction')),
            ],
        ),
    ]
