# Generated by Django 4.1.2 on 2023-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_rename_time_weaklyboard_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaklyboard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
