# Generated by Django 4.1.2 on 2023-12-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_alter_weaklyboard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaklyboard',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weaklyboard',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
