# Generated by Django 4.1.2 on 2023-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_weaklyboard_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaklyboard',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weaklyboard',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
