# Generated by Django 4.1.2 on 2023-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_remove_weaklyboard_date_alter_weaklyboard_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
