# Generated by Django 4.1.2 on 2023-12-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_teammember_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='video',
        ),
    ]
